# Generated by Django 5.2.1 on 2025-05-24 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glace', '0001_create_flavor_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scoops_left', models.PositiveIntegerField(default=40)),
                ('capacity', models.PositiveIntegerField(default=40)),
                ('flavor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tub', to='glace.flavor')),
            ],
        ),
    ]
