version: "3.9"

services:
  db_nalo_glacier:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - ng-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend_nalo_glacier:
    container_name: backend_nalo_glacier
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile.backend
    volumes:
      - ./backend:/code/backend
      - /code/backend/static
    ports:
      - "8000:8000"
    depends_on:
      db_nalo_glacier:
        condition: service_healthy
    networks:
      - ng-network

  frontend_nalo_glacier:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        - ENVIRONMENT=${ENVIRONMENT}
    container_name: frontend_nalo_glacier
    networks:
      - ng-network
    restart: always
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - ./frontend:/app
    env_file:
      - .env.local
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev

volumes:
  postgres_data:

networks:
  ng-network:
    external: true
