
FROM node:18-alpine

WORKDIR /app

# Copy only package.json and lock to install deps
COPY frontend/package*.json ./

RUN npm install

# Copy rest of frontend project
COPY frontend/ .

RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "dev"]