

FROM node:18-alpine
ARG ENVIRONMENT=dev

ENV ENVIRONMENT=${ENVIRONMENT}

WORKDIR /app

# Copy only package.json and lock to install deps
COPY frontend/package*.json ./

RUN npm install

# Copy rest of frontend project
COPY frontend/ .

EXPOSE 3000

RUN if [ "$ENVIRONMENT" = "prod" ]; then npm run build; fi

# At runtime
CMD ["sh", "-c", "if [ \"$ENVIRONMENT\" = 'prod' ]; then npx serve -s dist -l 80; else npm run dev; fi"]